# Generated by Django 5.1.4 on 2025-01-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userblog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userblog',
            options={'ordering': ('date_created',)},
        ),
    ]
