# Generated by Django 5.1.4 on 2025-01-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userblog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.userblog'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='category',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='user_blogs', to='core.category'),
        ),
    ]
