# Generated by Django 5.1.4 on 2025-01-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_comment_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
