# Generated by Django 5.1.5 on 2025-01-28 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_comment_author_alter_userblog_headline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
    ]
