# Generated by Django 5.1.5 on 2025-01-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='body',
            field=models.TextField(max_length=4000),
        ),
    ]
