# Generated by Django 5.1.4 on 2025-03-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notifications_body_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_created']},
        ),
    ]
