# Generated by Django 5.1.4 on 2025-03-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
    ]
