# Generated by Django 5.1.5 on 2025-01-27 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['date_modified']},
        ),
        migrations.AlterModelOptions(
            name='slugmessages',
            options={'ordering': ['time_sent']},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='members',
            new_name='slugs',
        ),
        migrations.AlterField(
            model_name='slugmessages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slugmessages',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
