# Generated by Django 5.1.4 on 2025-03-21 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0002_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-date_modified']},
        ),
    ]
