# Generated by Django 5.1.4 on 2025-03-27 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0003_alter_conversation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='engaged',
            field=models.ManyToManyField(related_name='active_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
