# Generated by Django 5.1.4 on 2025-04-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0004_conversation_engaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='slugmessages',
            name='is_indicator_message',
            field=models.BooleanField(default=False),
        ),
    ]
