# Generated by Django 5.1.4 on 2025-04-06 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0006_alter_slugmessages_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='engaged',
        ),
        migrations.AddField(
            model_name='conversation',
            name='disengaged',
            field=models.ManyToManyField(related_name='archived_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
