# Generated by Django 5.1.4 on 2025-03-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(default='Happy to be here!', max_length=755),
        ),
    ]
