# Generated by Django 5.1.4 on 2025-04-10 03:27

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
