# Generated by Django 5.1.4 on 2025-04-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personalized_articles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
